// node tools/build.mjs が作るファイル（手で編集しない）
self.VERSION = 'c5681ffa93c8';
self.PRECACHE = [
  "./",
  "./icons/icon-192.png",
  "./icons/icon-512.png",
  "./icons/icon-maskable-512.png",
  "./index.html",
  "./manifest.webmanifest",
  "./src/core/audio.js",
  "./src/core/builder.js",
  "./src/core/env.js",
  "./src/core/input.js",
  "./src/core/interact.js",
  "./src/core/props.js",
  "./src/core/terrain.js",
  "./src/core/textures.js",
  "./src/core/ui.js",
  "./src/core/util.js",
  "./src/main.js",
  "./src/scenes/akanoe.js",
  "./src/scenes/beppu.js",
  "./src/scenes/chiburi.js",
  "./src/scenes/komukai.js",
  "./src/scenes/mapdata.js",
  "./src/scenes/sea.js",
  "./src/scenes/stage.js",
  "./src/story/chapters.js",
  "./src/story/director.js",
  "./src/story/sources.js",
  "./style.css",
  "./vendor/three/LICENSE",
  "./vendor/three/three.module.min.js",
  "./vendor/three/utils/BufferGeometryUtils.js"
];
